### ISSUE TITLE
The future of Laravel-lang

### ISSUE THREAD

**Issue by caouecs** [Laravel-Lang/lang#1296]
I started this repository the 30 May 2013, with the help of Evgeny Kovalev, because Taylor Otwell didn't want to manage translations directly in Laravel Framework. We started with French, Russian, Dutch, Polish, Turk and Chinese versions, and now, we have 75 languages in the package.

I admit that sometimes, I merged pull requests without review ; most of the time, because I didn't understand the language ( I'm French you know ). But I try to check some translations, the homogeneity and coherence of words, but it's not easy. Because some prefer to use this or that word for an expression, or because such a word is better for his project... Sometimes, I ask the review of another person, sometimes, with some authors, I know I can merge immediately. But, it's not optimal for the quality of translations.

I don't say I want to stop, just take it easy, and I think it's time to detach this project from my Github account, create a new organization to manage it, include persons which will review pull requests and will choice the future of this project.

So I'm open for proposition about the name of organization ( Laravel-Lang ? ) and who want to join it.

> [Migration project](https://github.com/orgs/Laravel-Lang/projects/1)

Ideas :

 * list of [referents](https://github.com/Laravel-Lang/lang/blob/master/referents.md) by language : they are sollicited for a merge

**Comment by WhereIsLucas** [comment]
I like the idea of a gh organisation, and I can help for the french translation.
I think laravel-lang is a good idea!

**Comment by caouecs** [comment]
Yes, a list of referent by language is a good idea

**Comment by andrey-helldar** [comment]
Laravel-Lang is a great idea and the namespace is free.

I can be responsible for the Russian-language translation of files.

![image](https://user-images.githubusercontent.com/10347617/88532442-48a2c300-d00d-11ea-9abb-b6e8cb8380d3.png)

**Comment by andrey-helldar** [comment]
I see several options:

> For all options, you definitely need to separate the namespaces:
>
> https://github.com/Laravel-Lang
>   /en
>   /fr
>   /ru
>   /...

Option 1:
Only translation files are stored in the repositories, and they will be installed by a common package.

Option 2:
Make each localization self-contained.
```
composer require laravel-lang/en
composer require laravel-lang/fr
composer require laravel-lang/ru
composer require laravel-lang/...
```

At the same time, create a common package for installing all locales:
```
composer require laravel-lang/main
```

Or leave this choice for package managers

**Comment by andrey-helldar** [comment]
I want to say that you need to think over the actions in such a way that the user does not install all localizations at all as dependencies. So I'm thinking about how best to do the process of installing and updating packages.

@caouecs, @arcanedev-maroc, what do you think?

**Comment by andrey-helldar** [comment]
I want to say that you need to think over the actions in such a way that the user does not install all localizations at all as dependencies. So I'm thinking about how best to do the process of installing and updating packages.

@overtrue, @arcanedev-maroc, what do you think?

**Comment by caouecs** [comment]
75 repositories ?

**Comment by andrey-helldar** [comment]
Therefore, I doubt this option.Best Regards    Andrey Helldar14:47, 27 июля 2020 г., Fred Delrieu <notifications@github.com>:
75 repositories ?

**Comment by jorgercosta** [comment]
I don't mind taking over pt_PT.

**Comment by andrey-helldar** [comment]
@caouecs, maybe create a table with the names of those who are ready to be responsible for localizations?
In my opinion, this will make it easier for us and for those who want to take an active part in the life of the package.

| Lang | Assignee |
| --- |:--|
| ar | |
| az | |
| be | |
| bg | |
| bn | |
| bs | |
| ca | |
| cs | |
| cy | |
| da | |
| de | |
| de_CH | |
| el | |
| es | |
| et | |
| eu | |
| fa | |
| fi | |
| fil | |
| fr | @caouecs, @WhereIsLucas |
| gl | |
| he | |
| hi | |
| hr | |
| hu | |
| hy | |
| id | |
| is | |
| it | |
| ja | |
| ka | |
| kk | |
| km | |
| kn | |
| ko | |
| lt | |
| lv | |
| me | |
| mk | |
| mn | |
| mr | |
| ms | |
| nb | |
| ne | |
| nl | |
| nn | |
| pl | |
| ps | |
| pt | @jorgercosta |
| pt_BR | |
| ro | |
| ru | @andrey-helldar |
| sc | |
| si | |
| sk | |
| sl | |
| sq | |
| sr_Cyrillic | |
| sr_Latin | |
| sv | |
| sw | |
| tg | |
| th | |
| tk | |
| tl | |
| tr | |
| ug | |
| uk | |
| ur | |
| uz_Cyrillic | |
| uz_Latin | |
| vi | |
| zh_CN | |
| zh_HK | |
| zh_TW | |

**Comment by caouecs** [comment]
I copied the table in the subject

**Comment by caouecs** [comment]
> I don't mind taking over pt_PT.

Other question : we work with pt or pt_PT ? fr or fr_FR ? etc...

**Comment by andrey-helldar** [comment]
> I copied the table in the subject

Ok. I removed the table from my post :)

**Comment by jorgercosta** [comment]
> > I don't mind taking over pt_PT.
> 
> Other question : we work with pt or pt_PT ? fr or fr_FR ? etc...

i think we should go with language tags 
https://www.w3.org/International/questions/qa-choosing-language-tags

**Comment by WhereIsLucas** [comment]
@caouecs  I can manage **nl** and **de** translations too btw!

I think it would be great to have scripted installation for the package, by using publishing, making it easier to use for a wide range of users. I  copy-paste the files, but I think it's not the most efficient way to do it.

Another way could be a package "main" which contains just a download script, downloading the required files directly from the corresponding repo and installing them where needed.

* laravel-lang/main
* laravel-lang/langs

Usage could be like :  
`php artisan laravel-lang:install fr`

What do you think of this architecture?

**Comment by andrey-helldar** [comment]
@WhereIsLucas, https://github.com/andrey-helldar/laravel-lang-publisher 😉

**Comment by jensstigaard** [comment]
I can be responsible for the danish translation.

**Comment by caouecs** [comment]
## Projects based on this package

* [LaravelLang by ARCANEDEV](https://github.com/ARCANEDEV/LaravelLang) - Translations manager and checker for Laravel.
* [Laravel-lang by overtrue](https://github.com/overtrue/laravel-lang) - Command to add languages in your project.
* [laravel-lang-publisher by Andrey Helldar](https://github.com/andrey-helldar/laravel-lang-publisher) - Easy installation and update of translation files for your project.

**Comment by WhereIsLucas** [comment]
> @WhereIsLucas, https://github.com/andrey-helldar/laravel-lang-publisher

Didn't see the projects, this could be great to combine the projects into the organization?

**Comment by andrey-helldar** [comment]
> > @WhereIsLucas, https://github.com/andrey-helldar/laravel-lang-publisher
> 
> Didn't see the projects, this could be great to combine the projects into the organization?

What I mean is that the Laravel Lang package provides translation source files. Translation managers are responsible for publishing translations within the framework.
Now Fred is changing his style of work. As soon as he provides new data, translation managers will be added to his support.

**Comment by 360157** [comment]
hello, I can take over the Ukrainian localization

**Comment by caouecs** [comment]
> hello, I can take over the Ukrainian(uk) localization

Hello, 
it's your first time on this project, no ?

You can help on json and validation-inline 👼 

https://github.com/caouecs/Laravel-lang/blob/master/todo.md#uk

Thanks

**Comment by andrey-helldar** [comment]
@MrAlKuz, ping

**Comment by dbasechhetri** [comment]
I want to contribute to Nepali language.
I can be responsible for the Nepali or Nepalese (नेपाली) translation.

**Comment by caouecs** [comment]
> I want to contribute to Nepali language.
> I can be responsible for the Nepali or Nepalese (नेपाली) translation.

https://github.com/caouecs/Laravel-lang/blob/master/todo.md#ne thank you ;)

**Comment by MrAlKuz** [comment]
Greetings, thanks for the invitation to the project, I will be happy to
help in the development and prosperity of this business, I also want to
immediately notice that the "UK" code (United Kingdom) is not correct for
Ukraine, but "UA" is correct

ср, 5 авг. 2020 г. в 20:28, Fred Delrieu <notifications@github.com>:

**Comment by caouecs** [comment]
We follow ISO-639-1 and Ukrainian is UK https://en.wikipedia.org/wiki/Ukrainian_language

**Comment by andrey-helldar** [comment]
> Greetings, thanks for the invitation to the project, I will be happy to help in the development and prosperity of this business, I also want to immediately notice that the "UK" code (United Kingdom) is not correct for Ukraine, but "UA" is correct

Country abbreviation - UA
Language abbreviation - UK

**Comment by vdanny** [comment]
Hi, I'd like to contribute on Bahasa Indonesia (ID)

**Comment by LukaLatkovic** [comment]
@caouecs I meant to manage Serbian translations :) and help with organisation :)

**Comment by AdrianEdy** [comment]
Hello, I can help you to manage the Indonesian language (ID)

**Comment by caouecs** [comment]
> Hello, I can help you to manage the Indonesian language (ID)

Can you translate validation-inline.php and id.json ?

**Comment by AdrianEdy** [comment]
> > Hello, I can help you to manage the Indonesian language (ID)
> 
> Can you translate validation-inline.php and id.json ?

Sure

**Comment by Khuthaily** [comment]
Thank you, @caouecs. This is a great project. As a native speaker and [college-level professor of Arabic (and linguistics)](https://hs.umt.edu/wlc/arabic/faculty.php?s=Huthaily), I will be glad to take care of (or/and help with) Arabic.

**Comment by mohamedsabil83** [comment]
Good idea @caouecs. that's will keep all translations updated and been more trusted. So, I'll take care of Arabic as always

**Comment by caouecs** [comment]
two managers for Arabic ? No problem, if it's ok for you ;)

**Comment by andrey-helldar** [comment]
> two managers for Arabic ? No problem, if it's ok for you ;)

I'll just leave it here 😀

![image](https://user-images.githubusercontent.com/10347617/92572582-4cbd3400-f28d-11ea-946d-532be63fd3d9.png)

**Comment by andrey-helldar** [comment]
> two managers for Arabic ? No problem, if it's ok for you ;)

I think two heads are better than one. If there are any nuances in translation and perception, @Khuthaily and @mohamedsabil83 will be able to discuss this and choose the best option. Do you agree?

**Comment by mohamedsabil83** [comment]
> > two managers for Arabic ? No problem, if it's ok for you ;)
> 
> I think two heads are better than one. If there are any nuances in translation and perception, @Khuthaily and @mohamedsabil83 will be able to discuss this and choose the best option. Do you agree?

Totally agree with you

**Comment by caouecs** [comment]
done ;)

**Comment by andrey-helldar** [comment]
@caouecs, can you invite @Khuthaily to [our team](https://github.com/orgs/Laravel-Lang/people)?

**Comment by caouecs** [comment]
I did it this morning ( French hour of course )

**Comment by hugomeruma** [comment]
@caouecs I noticed that some translations are missing in Jetstream. I would like to know if there are plans for supporting Jetstream and I could help with the dutch translations for it.

**Comment by andrey-helldar** [comment]
@hugomeruma,
[Laravel Jetstream](https://github.com/laravel/jetstream) is a preset package. It does not use the "trans" method calls in the code or the "@lang" methods in the Blade templates.
This package connects to your application, where translation files should already be or one of the [translation managers](https://github.com/Laravel-Lang/lang#projects-based-on-this-package) installed.

When you install Jetstream, the package publishes the [template files](https://github.com/laravel/jetstream#what-is-installed) in which you need to make a localization call.

**Comment by caouecs** [comment]
+1 for @andrey-helldar comment and I think the project needs a work about localization.

So, for the moment, the best is to do pull requests to laravel-jetstream for localization, and after, I think it will be possible to create a new package for translation of laravel-jetstream

**Comment by Khuthaily** [comment]
> > > two managers for Arabic ? No problem, if it's ok for you ;)
> > 
> > 
> > I think two heads are better than one. If there are any nuances in translation and perception, @Khuthaily and @mohamedsabil83 will be able to discuss this and choose the best option. Do you agree?
> 
> Totally agree with you

Perfect; thank you, @caouecs, @mohamedsabil83, and @andrey-helldar.

**Comment by andrey-helldar** [comment]
@caouecs, I began to notice the emergence of questions indirectly related to this topic.
I think it can be closed, and new questions can be posted in new issues.

**Comment by caouecs** [comment]
ok
