### ISSUE TITLE
DE: recommendation

### ISSUE THREAD

**Issue by michabbb** [Laravel-Lang/lang#1311]
https://github.com/caouecs/Laravel-lang/blob/8cf07e05c5b2dd812046a62d30e5ccf3ec1e3ac2/src/de/validation.php#L148

i would like to recommend adding here:

`'pcode'                 => 'Postleitzahl',`

**Comment by michabbb** [comment]
@caouecs  ?????

**Comment by caouecs** [comment]
if you want to add it, do a pull request ;)

**Comment by michabbb** [comment]
@caouecs and which key-name for "postal code" do you prefer?

**Comment by caouecs** [comment]
proposes and the team will choose

**Comment by michabbb** [comment]
why should I post first, beside the fact you are the person who clearly has a problem, I asked you twice, but instead of reading you are repeating yourself - what a stupid attitude.... someone wants to help but the only thing you provide is useless time wasting unconstructive Postings... well done, hopefully you feel proud of this nonsense here....
