### ISSUE TITLE
Packagist doesn't know the new package name

### ISSUE THREAD

**Issue by mortenscheel** [Laravel-Lang/lang#1319]
Composer throws an error when running `composer require laravel-lang/lang` (with or without version) saying it couldn't find a matching package.

According to [Packagist](https://packagist.org/packages/caouecs/laravel-lang), the name is still `caouecs/laravel-lang`

**Comment by MyPuppet** [comment]
我也有同样的问题，切换了阿里云和官方源，也尝试过清理缓存。

**Comment by caouecs** [comment]
I check

**Comment by caouecs** [comment]
> 我也有同样的问题，切换了阿里云和官方源，也尝试过清理缓存。

in english, please

**Comment by caouecs** [comment]
@mortenscheel @MyPuppet Can you test again ?

**Comment by andrey-helldar** [comment]
@mortenscheel, the package namespace was changed. Now everything is all right. Check it out.

![image](https://user-images.githubusercontent.com/10347617/91955212-8630f500-ed0b-11ea-99bf-913b0bf979b2.png)

**Comment by caouecs** [comment]
sorry for the disagreement, I thought that Packagist would do the migration on its own

**Comment by andrey-helldar** [comment]
@caouecs, nothing wrong. When installing the package "caouecs / laravel-lang", packagist gives a warning that it is abandoned. But it still installs.
To use the new namespace, you need to manually update it.

![image](https://user-images.githubusercontent.com/10347617/91956563-7dd9b980-ed0d-11ea-8873-53d3dfb6486d.png)

**Comment by MyPuppet** [comment]
> @mortenscheel @MyPuppet Can you test again ?

Everything is normal now, thank you for your contribution.

**Comment by mortenscheel** [comment]
Thanks for the fix!
