### ISSUE TITLE
Communication with translation publisher

### ISSUE THREAD

**Issue by andrey-helldar** [Laravel-Lang/lang#1321]
Yesterday @caouecs added a new repository name to [Packagist](https://packagist.org/packages/laravel-lang/lang).
Update source in your packages:

- [x] [Lang Publisher](https://github.com/andrey-helldar/laravel-lang-publisher) by @andrey-helldar 
- [x] [LaravelLang](https://github.com/ARCANEDEV/LaravelLang) by @arcanedev-maroc 
- [x] [Laravel-lang](https://github.com/overtrue/laravel-lang) by @overtrue

**Comment by arcanedev-maroc** [comment]
It will be available on my major release (Laravel 8) https://github.com/ARCANEDEV/LaravelLang/pull/40

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-lang/commit/21f48d5854ac7c98eb9ee964df2fd67b4638441b

**Comment by andrey-helldar** [comment]
@caouecs, Hello! We are ready :-)
