### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by caouecs** [Laravel-Lang/lang#1334]
I updated some informations on this package to include Laravel 8 support.

All is ok for you ?

**Comment by andrey-helldar** [comment]
Yep 😊 Thanks!

**Comment by luisprmat** [comment]
I'd like translations to Laravel Jetstream (new autentication scaffolding) . I wish to contribute for spanish

**Comment by andrey-helldar** [comment]
@luisprmat, see this: https://github.com/Laravel-Lang/lang/issues/1296#issuecomment-689582324

**Comment by luisprmat** [comment]
Reviewing **Laravel jetstream** in this moment is supporting translations, most of the translatable texts in each of its components are using the notation `{{ __(' ') }}` ( I have sent some PR about it ). So it is time to think about how we would go about contributing. If a specific package will be created or translations are included in the main `--.json` of the Laravel Lang. I'd like contribute with spanish (`es.json`)

**Comment by andrey-helldar** [comment]
@caouecs, to be honest, I would add Jetstream translations to existing json files.

**Comment by andrey-helldar** [comment]
@caouecs, to be honest, I would add Jetstream translations to existing json files.

I think this is correct because Laravel Jetstream is a package for the framework and essentially uses its translation files.
Therefore, I think it is wrong to create separate ones.

**Comment by andrey-helldar** [comment]
> Reviewing **Laravel jetstream** in this moment is supporting translations, most of the translatable texts in each of its components are using the notation `{{ __(' ') }}` ( I have sent some PR about it ). So it is time to think about how we would go about contributing. If a specific package will be created or translations are included in the main `--.json` of the Laravel Lang. I'd like contribute with spanish (`es.json`)

See #1335

**Comment by caouecs** [comment]
@andrey-helldar to be honest, the question is for the team ;)

it's possible to have a poll in Github issue ?

**Comment by andrey-helldar** [comment]
@caouecs, I'm not sure about the polls, but the discussions can somehow be turned on. For example, https://github.com/laravel/framework/discussions

**Comment by caouecs** [comment]
I just found that : https://github.com/orgs/Laravel-Lang/teams/laravel-lang/discussions
but via the team, not the project

**Comment by andrey-helldar** [comment]
maybe there is something [here](https://docs.github.com/en/github/building-a-strong-community/creating-a-team-discussion)?

**Comment by caouecs** [comment]
the same thing that I wrote ;)

**Comment by caouecs** [comment]
but it's different than your example with laravel framework, I don't know how to activate it on this project

**Comment by andrey-helldar** [comment]
> but it's different than your example with laravel framework, I don't know how to activate it on this project

I found information that discussions now only work for teams. For repositories, they are still being tested (https://github.com/vercel/vercel/discussions/3874#discussioncomment-2627)
I can assume that Taylor turned them on at a personal request.

**Comment by luisprmat** [comment]
Regardless of the organization that will be given to this project, here is my humble contribution to jetstream translations for the Spanish language. See [#1336 ](https://github.com/Laravel-Lang/lang/pull/1336)

**Comment by andrey-helldar** [comment]
I added a discussion to the team: https://github.com/orgs/Laravel-Lang/teams/laravel-lang/discussions

**Comment by dbasechhetri** [comment]
Adding to existing is easy and not confusing than Separate files

**Comment by andrey-helldar** [comment]
I think this question can be closed.

**Comment by LukaLatkovic** [comment]
> Adding to existing is easy and not confusing than Separate files

I agree, it is just a package for Laravel so it should be in same json file, but maybe there will be more lines for the Jetstream and thus a special file will be made just for it, but that will be seen in the future

**Comment by andrey-helldar** [comment]
I think we have solved the Laravel 8 question here, and the new posts are about Laravel Jetstream. I created a [discussion](https://github.com/Laravel-Lang/lang/discussions/1344) on this subject.
