### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by DA40** [Laravel-Lang/lang#1337]
While doing a composer update today on a Laravel 7 application I got this message:

Package caouecs/laravel-lang is abandoned, you should avoid using it. Use https://github.com/Laravel-Lang/lang instead.

Is that true?

**Comment by cotiga** [comment]
no
It's just the name that have changed

**Comment by andrey-helldar** [comment]
@DA40, the package used to be in the @caouecs namespace, but recently he moved it to the organization.

All you have to do is change the package name in the composer.lock file or use one of the three [translation managers](https://github.com/Laravel-Lang/lang#projects-based-on-this-package). For example, [andrey-helldar/laravel-lang-publisher](https://github.com/andrey-helldar/laravel-lang-publisher).

**Comment by DA40** [comment]
Thanks guys.  It's a dependency on overtrue/laravel-lang which I resolved by updating to its latest release.
