### ISSUE TITLE
Update todo.md

### ISSUE THREAD

**Issue by andrey-helldar** [Laravel-Lang/lang#1355]
@caouecs, can you update the todo.md file after you accept the PR?

**Comment by caouecs** [comment]
Yes, I finish PR before ;)

**Comment by andrey-helldar** [comment]
Yes of course)

I did not generate the file to avoid merge conflicts.

**Comment by caouecs** [comment]
done ;)

**Comment by andrey-helldar** [comment]
Thanks!
