### ISSUE TITLE
Translate missing keys for few languages

### ISSUE THREAD

**Issue by andrey-helldar** [Laravel-Lang/lang#1357]
| | what | who |
| :---: | :---: | :--- |
| #1339 | [ar](https://github.com/Laravel-Lang/lang/blob/master/todo.md#ar) | @mohamedsabil83, @Khuthaily (see also #1339) |
| | [da](https://github.com/Laravel-Lang/lang/blob/master/todo.md#da) | @jensstigaard |
| | [de](https://github.com/Laravel-Lang/lang/blob/master/todo.md#de) | @WhereIsLucas |
| | [fr](https://github.com/Laravel-Lang/lang/blob/master/todo.md#fr) | @caouecs, @WhereIsLucas |
| | [nl](https://github.com/Laravel-Lang/lang/blob/master/todo.md#nl) | @WhereIsLucas |
| #1358 | [pt](https://github.com/Laravel-Lang/lang/blob/master/todo.md#pt) | @jorgercosta |
| #1363 | [sr_Cyrillic](https://github.com/Laravel-Lang/lang/blob/master/todo.md#sr_Cyrillic) | @LukaLatkovic |
| #1363 | [sr_Latin](https://github.com/Laravel-Lang/lang/blob/master/todo.md#sr_Latin) | @LukaLatkovic |
| | [uk](https://github.com/Laravel-Lang/lang/blob/master/todo.md#uk) | @MrAlKuz |
| | [zh_CN](https://github.com/Laravel-Lang/lang/blob/master/todo.md#zh_CN), [zh_HK](https://github.com/Laravel-Lang/lang/blob/master/todo.md#zh_HK), [zh_TW](https://github.com/Laravel-Lang/lang/blob/master/todo.md#zh_TW) | @overtrue |

Can you update your languages?

**Comment by jorgercosta** [comment]
[pt] done  #1358, cheers!

**Comment by mohamedsabil83** [comment]
[ar] done #1339 :coffee:

**Comment by luisprmat** [comment]
I would say that there are many languages ​​missing to translate mainly the `.json`

**Comment by andrey-helldar** [comment]
> I would say that there are many languages ​​missing to translate mainly the `.json`

I agree. But we have no [referents](https://github.com/Laravel-Lang/lang/blob/master/referents.md) for other languages :(
