### ISSUE TITLE
Laravel 8 - missing paginator translations (tailwind)

### ISSUE THREAD

**Issue by xorock** [Laravel-Lang/lang#1359]
Hello,
In Laravel 8 Tailwind paginator has new translation keys:

```php
{!! __('Showing') !!}
<span class="font-medium">{{ $paginator->firstItem() }}</span>
{!! __('to') !!}
<span class="font-medium">{{ $paginator->lastItem() }}</span>
{!! __('of') !!}
<span class="font-medium">{{ $paginator->total() }}</span>
{!! __('results') !!}
```

I don't see translation in any language.

**Comment by caouecs** [comment]
it's very bad for translations... not good for right to left language, and not adaptation for results if we have just one result...

'{0} No item|[1]  Showing :firstItem to :lastItem of :totalItems result |[2,*] Showing :firstItem to :lastItem of :totalItems results'

**Comment by caouecs** [comment]
do you have source of this code please ?

**Comment by mohamedsabil83** [comment]
@caouecs he means this https://github.com/illuminate/pagination/blob/c5da788f8c7cf7c24a43d60b9bcf0b992457c30c/resources/views/tailwind.blade.php#L28-L34

I advice to add it

**Comment by andrey-helldar** [comment]
I can see other keys accessed through the pagination (https://github.com/illuminate/pagination/blob/c5da788f8c7cf7c24a43d60b9bcf0b992457c30c/resources/views/tailwind.blade.php#L6).

I will try to send PR to the project.

**Comment by luisprmat** [comment]
I had sent a PR [#1361 ](https://github.com/Laravel-Lang/lang/pull/1361)

**Comment by andrey-helldar** [comment]
See https://github.com/illuminate/pagination/blob/c5da788f8c7cf7c24a43d60b9bcf0b992457c30c/resources/views/tailwind.blade.php#L74

![image](https://user-images.githubusercontent.com/10347617/94150343-b0488380-fe81-11ea-9842-e4dca0c44a46.png)

**Comment by luisprmat** [comment]
@andrey-helldar Added **"Go to page :page"** to PR, the others translation seem to be

**Comment by luisprmat** [comment]
@caouecs (https://github.com/Laravel-Lang/lang/issues/1359#issuecomment-698295606) If there is only one result, the pagination component is not displayed by default. But it is convenient to add a PR to Laravel to improve the translation support for right-left languages

**Comment by andrey-helldar** [comment]
I sent a PRs: https://github.com/laravel/framework/pull/34518 and https://github.com/laravel/laravel/pull/5426

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/94155061-34513a00-fe87-11ea-8add-b527f18cd692.png)

**Comment by mohamedsabil83** [comment]
My language is RTL (Arabic) and I can say that there is no need to make any improvements to the pagination

**Comment by luisprmat** [comment]
@mohamedsabil83 Those are good news!

**Comment by andrey-helldar** [comment]
There is a problem with the Russian language.

The full phrase in heather sounds like this:
`Showing 4 to 8 of 32 results`

In Russian, it will be correct:
`Показано с 4 по 8 из 32 результатов`

In the current scheme, the translation will be incorrect.

There are two solutions:
1. `Показано 4 - 8 из 32 результатов`
2.
```
"Showing": "Показано с",
"to": "по",
"of": "из",
"results": "результатов"
```

The second option is bad because the word "showing" can be used elsewhere.

At the same time, in Russian, the "to" particle is translated depending on the context.
For example:
| | |
|-|-|
| Come **to** the table | Подойти **к** столу |
| 3 **to** 5 entries | с 3 **по** 5 записей |

Since now the word "Showing" is used only in one place, I suggest using the second option, as it is more acceptable for display.
And when this word is used somewhere else, then I will think about how best to choose the context.

**Comment by luisprmat** [comment]
@andrey-helldar, in Spanish it happens exactly the same, so I applied a solution very similar to yours. I think that as long as these words ("Showing", "to", "of", ... ) are only used in the context of pagination there will be no problem. The translation does not have to be so literal, the idea is to keep the coherence of the phrase shown in this specific context.
If there are changes in the future we will review

**Comment by andrey-helldar** [comment]
Exactly. Now I propose to do so, and then we'll see.

**Comment by luisprmat** [comment]
At the moment it would only be missing for @caouecs to update the `todo.md` file to be able to close this issue! (And of course complete the translations of the other languages)

**Comment by andrey-helldar** [comment]
![S00924-200310](https://user-images.githubusercontent.com/10347617/94176715-2b6d6200-fea1-11ea-9501-dc702b4c98bf.jpg)

**Comment by caouecs** [comment]
If they don't want to update the code, we can propose it in a package

**Comment by andrey-helldar** [comment]
> If they don't want to update the code, we can propose it in a package

So we sent some PRs)

**Comment by xorock** [comment]
Just found another issue in base template: https://github.com/illuminate/pagination/blob/c5da788f8c7cf7c24a43d60b9bcf0b992457c30c/resources/views/tailwind.blade.php#L2 
aria-label is not translated.

**Comment by andrey-helldar** [comment]
> Just found another issue in base template: https://github.com/illuminate/pagination/blob/c5da788f8c7cf7c24a43d60b9bcf0b992457c30c/resources/views/tailwind.blade.php#L2
> aria-label is not translated.

Thanks! I sent a PR: https://github.com/laravel/framework/pull/34568

**Comment by andrey-helldar** [comment]
PR was merged: https://github.com/laravel/framework/pull/34568 😊

My PR for this repo: https://github.com/Laravel-Lang/lang/pull/1368

**Comment by andrey-helldar** [comment]
The problem from the first message has been resolved, so I close the issue.
