### ISSUE TITLE
the 'ToDo' generator ignores the additional information

### ISSUE THREAD

**Issue by olsza** [Laravel-Lang/lang#1377]
The "ToDo" generator does not take into account whether there are translated rules that have more versions, e.g. "size" has additional information such as: "numeric", "file", "string", "array", which are e.g. in the validation.php file, i.e. like any of the additional information, not have been translated, this information is not displayed in doto.md.
[
![Zrzut ekranu z 2020-09-30 15-44-36](https://user-images.githubusercontent.com/12556170/94693631-3fe3ab80-0334-11eb-90f3-674b4ab807b6.png)
](url)
I found an error during the discussion https://github.com/Laravel-Lang/lang/discussions/1376#discussion-22091

**Comment by olsza** [comment]
you can assign me to this task, which was reported by BUG himself, I will take care of in the weekend or next week.
I would assign to this report myself, but I don't have this option :/

**Comment by luisprmat** [comment]
Have you thought about using automated tests on this package with **PHPUnit**? It would be useful to test the actions of `script/todo.php` and debug bugs preventing them from appearing again in the future.

**Comment by jmucoder** [comment]
@if($errors->any())
	@foreach ($errors->all()as $error)

	<div class="alert alert-danger" role="alert">
     {{$error}}
</div>

	@endforeach
	
	@endif

**Comment by jmucoder** [comment]
where is error

**Comment by caouecs** [comment]
@jmucoder Go to [Laravel](https://laravel.com/) for your question ? Thank you

**Comment by olsza** [comment]
I am sending a projection of the solution, how is the translation extended, it is a dot added, but I was wondering whether to give e.g. "->" instead of a dot
![Zrzut ekranu z 2020-10-06 13-24-57](https://user-images.githubusercontent.com/12556170/95196001-adca2000-07d7-11eb-8976-62770c98457a.png)

**Comment by luisprmat** [comment]
The dot notation is used by Laravel to access the sub-elements of an array, so that would be fine.

**Comment by olsza** [comment]
I just suggested Laravel with a dot, but I thought about "->" to make it more readable.
But I leave as it is - a dot ;)

**Comment by caouecs** [comment]
+1 for dot

**Comment by andrey-helldar** [comment]
+1.

**Comment by luisprmat** [comment]
+1 for dot

**Comment by olsza** [comment]
ok new branch and new Pull requests #1406 
@andrey-helldar the code is the same without any corrections
