### ISSUE TITLE
[en] tag * and - in json file

### ISSUE THREAD

**Issue by caouecs** [Laravel-Lang/lang#1563]
Hello,
it's normal ?

https://github.com/Laravel-Lang/lang/blob/1626917342f3ce20fcf95c376bce8b5441553bb1/script/en/en.json#L2

**Comment by caouecs** [comment]
I deleted in en.json

**Comment by olsza** [comment]
same last line that is ```"-": "-"```, what is this for ??

**Comment by andrey-helldar** [comment]
From a logical point of view, this is not normal.

But from Taylor's point of view: https://github.com/Laravel-Lang/lang/discussions/1547#discussioncomment-474033

![image](https://user-images.githubusercontent.com/10347617/112457543-edc49580-8d6c-11eb-9a16-9d3a567934dd.png)

**Comment by andrey-helldar** [comment]
Since there were a lot of new keys, I didn't think about placing them.

Generally yes, I agree that these keys have been removed from us. They obviously don't need a translation 😂
