### ISSUE TITLE
It doesn't possible to add new tags in source/en.json 

### ISSUE THREAD

**Issue by luisprmat** [Laravel-Lang/lang#1719]
- Laravel-Lang Version: 9.1.0
- PHP Version: 8.0.3

### Description:
It doesn't possible to add new tags in `source/en.json`. Tests don't pass and don't allow to do pull request.
Recently i added new translations for the new `Password` validation rule class and github actions generate errors in test

### Steps To Reproduce:
- Add a commit modifying `source/en.json`.
- Push and wait for running Github Actions workflow.

**Comment by caouecs** [comment]
There is error, but I was able to accept the pull request

**Comment by andrey-helldar** [comment]
I can check tomorrow

**Comment by andrey-helldar** [comment]
I remembered why the test was giving an error.

You added new keys to the `source/en.json` file, but did not add them to all languages.

In this case, we just accept the PR without paying attention to phpunit.

When the PR is accepted, an automatic script is launched that will put down all the necessary keys (`php app/keys.php`)

Therefore, when adding keys to any file from the `source` folder, phpunit should be ignored.
