### ISSUE TITLE
Parser deletes some existing tags for Laravel Jetstream

### ISSUE THREAD

**Issue by luisprmat** [Laravel-Lang/lang#1848]
- Laravel-Lang Version: 10.1.6
- PHP Version: 8.0.3

### Description:
In previous pull requests we add translations for all tags of laravel jetstream up to that moment. Among them (PR [#1393](https://github.com/Laravel-Lang/lang/pull/1393) and [#1394](https://github.com/Laravel-Lang/lang/pull/1394)) were the following that correspond to the file [`JetstreamWithTeamsServiceProvider`](https://github.com/laravel/jetstream/blob/2.x/stubs/app/Providers/JetstreamWithTeamsServiceProvider.php)
- *Administrator*
- *Administrator users can perform any action.*
- *Editor*
- *Editor users have the ability to read, create, and update.*

When installing a new project these tags remain untranslated although within Jetstream they still have translation support.

![Bug-llang](https://user-images.githubusercontent.com/9275870/133189660-29fc2e9c-7098-4d39-b274-70d485a3db3f.PNG)

But if I add these keys to the `es.json` they get translated automatically without doing anything else.

The main reasons for this behavior are:
- This parser looks for matches in the packages (breeze, fortify and jetstream) with strings [`'__('`, `'trans('`, `'@lang('`, `'Lang::get('`](https://github.com/Laravel-Lang/lang/blob/master/app/main/Support/Finder.php#L14) for select keys to translate and apply [regular expressions](https://github.com/Laravel-Lang/lang/blob/master/app/main/Support/Parser.php#L13) *deleting* keys that do not match any package.
- These tags wasn't ignored because they were wrapped in the operator `__(   )`, but recently in laravel jetstream these keys was taken out of this operator (PR [#837](https://github.com/laravel/jetstream/pull/837)) in favour of a new method `jsonSerialize()` so they were *removed* from json files with their translations.
- Even so the translations are supported within the [Role class](https://github.com/laravel/jetstream/blob/2.x/src/Role.php#L74-L75) so they work perfectly if the translations are added.
```bash
    public function jsonSerialize()
    {
        return [
            'key' => $this->key,
            'name' => __($this->name),
            'description' => __($this->description),
            'permissions' => $this->permissions,
        ];
    }
```
I would like to find a way that these tags are not excluded from the file [`source/packages/jetstream.json`](https://github.com/Laravel-Lang/lang/blob/master/source/packages/jetstream.json)

### Steps To Reproduce:

- Install a fresh Laravel application with Jetstream + Teams
```bash
laravel new my-app --jet
```
- Choose `livewire` stack with **teams**.
- Configure `.env` file (*database*, etc) and run migrations, install and run node dependencies
```bash
php artisan migrate
npm install && npm run dev
```
- Register an user
- Install and set a new language using translations of this package.
- Go to **Teams** dropdown, and *Team Settings*

**Comment by andrey-helldar** [comment]
This is problem. Dynamic keys can be absolutely anything, so the 100% regex will not work correctly.

I suggest a solution: add a new file, for example, `jetstream-ext.json` and save such keys to it.

**Comment by luisprmat** [comment]
Or modify the parser for not deleting the existing keys but merge with new found keys! More difficult? is there any disadvantage?

**Comment by andrey-helldar** [comment]
This is easy, but unnecessary.

We made automatic deletion on purpose to get rid of old keys.

**Comment by luisprmat** [comment]
The important issue is to provide a solution that allows adding and keeping those keys that do not match to any regular expression and that they can be merged with all `[locale].json` to be translated.

**Comment by andrey-helldar** [comment]
If I understand you correctly, then I propose to save the current structure with the addition of new files:

![image](https://user-images.githubusercontent.com/10347617/133611127-9ff8aaf6-1e30-4a03-a16c-c671ae2fb8bf.png)

**Comment by luisprmat** [comment]
It seems perfect, and leave open the possibility of whether in the future there are extras also for other packages to be able to add them. 
Remember that for the base files of the framework (although I think we are not doing automatic searches for it) there are also keys that do not match regular expressions such as those corresponding to the new password rule.

**Comment by andrey-helldar** [comment]
@luisprmat, see my #1859 PR 😎

**Comment by luisprmat** [comment]
Reviewed and approved!
