### ISSUE TITLE
Class "LaravelLang\Publisher\Concerns\BaseServiceProvider" not found  

### ISSUE THREAD

**Issue by FabienArr** [Laravel-Lang/lang#1944]
Hello,

I just do a composer update and now i have this problem :
U:\xampp\htdocs\extranetfvbd>composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.     
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ServiceProvider.php line 9:

  Class "LaravelLang\Publisher\Concerns\BaseServiceProvider" not found  

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

![image](https://user-images.githubusercontent.com/87081538/149625005-2067d179-6c3a-4163-8b80-ac56e268b0d8.png)

How can i resolve it ?
Regards

**Comment by andrey-helldar** [comment]
What version of `laravel-lang/lang` are you using?

**Comment by andrey-helldar** [comment]
@caouecs
![Screenshot_2022-01-15-19-27-21-580_com android chrome](https://user-images.githubusercontent.com/10347617/149629515-55b9c7ca-ebc8-4949-9b3c-e21cc3ffb717.jpg)
![Screenshot_2022-01-15-19-27-49-336_com android chrome](https://user-images.githubusercontent.com/10347617/149629516-82aa324c-6863-4841-bc69-3f57098a9074.jpg)

**Comment by andrey-helldar** [comment]
I created a [PR](https://github.com/Laravel-Lang/lang/pull/1945) to solve this problem when you are not using a [`publisher`](https://github.com/Laravel-Lang/publisher).

We will release a patch soon.

**Comment by andrey-helldar** [comment]
@FabienArr, as a quick fix you can install a [`publisher`](https://github.com/Laravel-Lang/publisher) (recommended).

**Comment by FabienArr** [comment]
Thanks, It work but now i have this 👍 
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\Breeze" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/Breeze.php" and "U:
/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\Breeze.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\Cashier" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/Cashier.php" and "
U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\Cashier.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\Fortify" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/Fortify.php" and "
U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\Fortify.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\Jetstream" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/Jetstream.php" a
nd "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\Jetstream.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\Laravel" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/Laravel.php" and "
U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\Laravel.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\Lumen" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/Lumen.php" and "U:/x
ampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\Lumen.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\Nova" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/Nova.php" and "U:/xam
pp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\Nova.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\SparkPaddle" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/SparkPaddle.ph
p" and "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\SparkPaddle.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Plugins\SparkStripe" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Plugins/SparkStripe.ph
p" and "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Plugins\SparkStripe.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\Provider" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/Provider.php" and "U:/xampp/htdoc
s/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\Provider.php", the first will be used.
Warning: Ambiguous class resolution, "LaravelLang\Lang\ServiceProvider" was found 2x: in "U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/lang/src/ServiceProvider.php" and "
U:/xampp/htdocs/extranetfvbd/vendor/laravel-lang/publisher/packages/lang\ServiceProvider.php", the first will be used.

**Comment by andrey-helldar** [comment]
@FabienArr, oh, sorry. My bad :)

Released: [`v11.2.0`](https://github.com/Laravel-Lang/publisher/releases/tag/v11.2.0).

Just run the `composer update`

**Comment by robbielove** [comment]
The install instructions suggest to require as a dev dependency but I found this did not work.
```
$ composer require laravel-lang/publisher
```

**Comment by andrey-helldar** [comment]
> The install instructions suggest to require as a dev dependency but I found this did not work.
> 
> ```
> $ composer require laravel-lang/publisher
> ```

What version of `laravel-lang/lang` are you using?

**Comment by andrey-helldar** [comment]
We have temporarily removed the publication of version 10.2. Run the `composer update` to revert to version 10.1.12.

**Comment by caouecs** [comment]
Sorry for the 10.2 version, it's my fault

**Comment by andrey-helldar** [comment]
My too 😔

**Comment by andrey-helldar** [comment]
We fixed this bug and re-released [`10.2.0`](https://github.com/Laravel-Lang/lang/releases/tag/10.2.0).

Just run the `composer update` to update your dependencies.
