### ISSUE TITLE
en.json appears to have unused items or they might be part of a package

### ISSUE THREAD

**Issue by madman-81** [Laravel-Lang/lang#1966]
- Laravel-Lang Version: Master
- PHP Version: n/a

### Description:
en.json has a few lines that I can't find in laravel/framework:

    "The :attribute must contain at least one letter.",
    "The :attribute must contain at least one number.",
    "The :attribute must contain at least one symbol.",
    "The :attribute must contain at least one uppercase and one lowercase letter.",
    "The given :attribute has appeared in a data leak. Please choose a different :attribute.",

They have been added with commit 7e54ef7

Are they really from the framework itself or from a package?

**Comment by andrey-helldar** [comment]
These are the password validation messages in Laravel: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Rules/Password.php
