### ISSUE TITLE
The status of translations on the WWW is not up to date

### ISSUE THREAD

**Issue by olsza** [Laravel-Lang/lang#2074]
### Environment

- Laravel-Lang Version: all
- Laravel Version: all
- PHP Version: all

### Issue description

The website https://laravel-lang.com/status.html is not up to date... There are full PL #2071  or IT #2072 translations and the status shows that it is not translated... Something GH Action did not start up well

### Steps to reproduce

https://laravel-lang.com/status.html

**Comment by olsza** [comment]
No longer valid, I see that it has been corrected and there are correct data.

**Comment by andrey-helldar** [comment]
Before processing https://github.com/Laravel-Lang/lang/pull/2073:

![image](https://user-images.githubusercontent.com/10347617/158808761-682a9062-8c7f-4b87-afcf-e0c7a6e0561c.png)

After processing:

![image](https://user-images.githubusercontent.com/10347617/158808937-ecd7f5ab-152c-436a-969d-a2a824b088df.png)
