### ISSUE TITLE
Mail notification subcopy isn't translated!

### ISSUE THREAD

**Issue by luisprmat** [Laravel-Lang/lang#2157]
### Environment

- Laravel-Lang Version: 10.7.2
- Laravel Version: 9.10.1
- PHP Version: 8.1.5

### Issue description

```php
@lang(
    "If you're having trouble clicking the \":actionText\" button, copy and paste the URL below\n".
    'into your web browser:',
    [
        'actionText' => $actionText,
    ]
) <span class="break-all">[{{ $displayableActionUrl }}]({{ $actionUrl }})</span>
```
[This text](https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Notifications/resources/views/email.blade.php#L53-L59) isn't translated. From we had the change to *laravel versions*, i don't know where i must put this translation to be processed by `keys.php` script.

### Steps to reproduce

- Install a fresh laravel application with jetstream (livewire).
- Setup email sent.
- Send a email

**Comment by andrey-helldar** [comment]
I created a file for such keys: https://github.com/Laravel-Lang/lang/pull/2158

**Comment by luisprmat** [comment]
This translation was lost in [this commit](https://github.com/Laravel-Lang/lang/commit/4a5b2ccdaaa4b65bd102cf71a39aba49ee589d1f) for many languages

**Comment by andrey-helldar** [comment]
@luisprmat, yes, thank you. I also remembered that I saw this key.

As the opportunity arises, I will restore it in all localizations.
