### ISSUE TITLE
/uk/ folder contains Russian translations

### ISSUE THREAD

**Issue by monkeyphysics** [Laravel-Lang/lang#2207]
### Environment

- Laravel-Lang Version: latest
- Laravel Version: latest
- PHP Version: latest

### Issue description

Pretty straightforward:
https://github.com/Laravel-Lang/lang/blob/main/locales/uk/validation.php

The files for the United Kingdom actually have Russian translations in there. 

### Steps to reproduce

View any file within https://github.com/Laravel-Lang/lang/blob/main/locales/uk/

**Comment by monkeyphysics** [comment]
Nvm, that's Ukrainian.

**Comment by andrey-helldar** [comment]
1. This is Ukrainian :)
2. You probably mixed up the country code and locale code.

See [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes):

| Country | Country Code | Locale Code |
|:---|:---:|:---:|
| English - Great Britain | uk | en |
| Ukraine | ua | uk |
