### ISSUE TITLE
"You're logged in!" missing for Laravel Breeze

### ISSUE THREAD

**Issue by markdegrootnl** [Laravel-Lang/lang#2269]
### Feature description

Laravel Breeze has the message "You're logged in!" on the Dashboard page, which is missing from the translations.

### Environment

- Laravel-Lang Version:
- Laravel Version:
- PHP Version:

**Comment by andrey-helldar** [comment]
Unfortunately, Laravel cannot translate words written without explicitly calling the `trans()` or `__()` helper.

Therefore, we do not translate such phrases.

See https://github.com/laravel/breeze/blob/1.x/stubs/inertia-react/resources/js/Pages/Dashboard.jsx#L17
