### ISSUE TITLE
The error message contains english text

### ISSUE THREAD

**Issue by ghostlexly** [Laravel-Lang/lang#2394]
### Environment

- Laravel-Lang Version: 12.0
- Laravel Version: 9
- PHP Version: 8.1

### Issue description

On the "message" attribute, we still have an English not translated text.

````JSON
{
    "message": "Le champ adresse e-mail est obligatoire. (and 1 more error)",
    "errors": {
        "email": [
            "Le champ adresse e-mail est obligatoire."
        ],
        "password": [
            "Le champ mot de passe est obligatoire."
        ]
    }
}
````

### Steps to reproduce

- Install Laravel-Lang/lang
- add the french language

````
php artisan lang:add fr
````

- send an api request with  multiple validations constraints.

**Comment by andrey-helldar** [comment]
@ghostlexly, it really is. We have not translated all the phrases yet.

You can see the current status of the translation [`here`](https://laravel-lang.com/statuses/fr.html).

**Comment by andrey-helldar** [comment]
@caouecs, @WhereIsLucas, can you help?

**Comment by caouecs** [comment]
I do

**Comment by andrey-helldar** [comment]
@ghostlexly, you can run the `composer update` command.
